
import type { Metadata } from "next";
import "./globals.css";
import SmoothScroll from "@/components/smooth-scroll";
import LoadingScreen from "@/components/animation/loading-screen";
import BackToTop from "@/components/back-to-top";




export const metadata: Metadata = {
  title: "NeoAI",
  description: "Generated by Open AI",
  icons: {
    icon:'/favicon.ico'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body className="font-mulish ">
        <SmoothScroll>
          {children}
          <BackToTop />
        </SmoothScroll>
      </body>
    </html>
  );
}
