import type { Metadata } from "next";
import "./globals.css";




export const metadata: Metadata = {
  title: "NeoAI",
  description: "Generated by Open AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-mulish">{children}</body>
    </html>
  );
}
